print("Welcome to the tip calculator!")
total_bill = float(input("What was the total bill? $"))
tip_percent = float(input("How much tip would you like to give? 10, 12, or 15? "))
split_count = int(input("How many people to split the bill? "))
total_amount = total_bill + (total_bill * tip_percent/100)
per_person_amount  = round(total_amount/split_count,2)
print(f"Each person should pay: ${per_person_amount}")